const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{ .preferred_optimize_mode = .ReleaseSmall });
    // Strip debug info from release binaries — debug sections can embed
    // absolute build paths and toolchain identifiers that break reproducible
    // builds across CI runners. Release workflow passes `-Dstrip=true`.
    const strip = b.option(bool, "strip", "Strip debug symbols") orelse (optimize != .Debug);

    const templates_src = generateTemplatesModule(b);

    const templates_mod = b.createModule(.{
        .root_source_file = templates_src,
        .target = target,
        .optimize = optimize,
        .strip = strip,
    });

    const completions_src = generateCompletionsModule(b);
    const completions_mod = b.createModule(.{
        .root_source_file = completions_src,
        .target = target,
        .optimize = optimize,
        .strip = strip,
    });

    const exe_mod = b.createModule(.{
        .root_source_file = b.path("src/main.zig"),
        .target = target,
        .optimize = optimize,
        .strip = strip,
    });
    exe_mod.addImport("templates_data", templates_mod);
    exe_mod.addImport("completions_data", completions_mod);

    const exe = b.addExecutable(.{
        .name = "zignore",
        .root_module = exe_mod,
    });
    b.installArtifact(exe);

    const run_cmd = b.addRunArtifact(exe);
    run_cmd.step.dependOn(b.getInstallStep());
    if (b.args) |args| run_cmd.addArgs(args);
    const run_step = b.step("run", "Run zignore");
    run_step.dependOn(&run_cmd.step);

    const test_mod = b.createModule(.{
        .root_source_file = b.path("tests.zig"),
        .target = target,
        .optimize = optimize,
    });
    test_mod.addImport("templates_data", templates_mod);
    test_mod.addImport("completions_data", completions_mod);
    const tests = b.addTest(.{ .root_module = test_mod });
    const run_tests = b.addRunArtifact(tests);
    const test_step = b.step("test", "Run unit tests");
    test_step.dependOn(&run_tests.step);
}

// Walk the github/gitignore subtree (vendor/github/gitignore), copying each
// *.gitignore from the top level and from Global/ into a synthetic WriteFiles
// dir, then emit templates_data.zig alongside so its @embedFile paths resolve
// against the copied files. The subtree is managed by `make update-subtrees`.
//
// Community/ is intentionally skipped — those templates are framework/IDE
// niche and bloat the binary without matching what users type.
//
// Collision policy: case-insensitive stem dedupe, top-level wins. The
// upstream curates these splits, so collisions are unexpected.
const VendorEntry = struct {
    namespace: []const u8,
    stem: []const u8, // preserved original casing
    source_path: []const u8, // relative path under the repo root
};

fn generateTemplatesModule(b: *std.Build) std.Build.LazyPath {
    var entries: std.ArrayList(VendorEntry) = .empty;
    defer entries.deinit(b.allocator);

    var seen: std.StringHashMap(void) = .init(b.allocator);
    defer seen.deinit();

    collectInternal(b, &entries, &seen);
    collectVendor(b, "github", "", &entries, &seen);
    collectVendor(b, "github", "Global", &entries, &seen);

    std.mem.sort(VendorEntry, entries.items, {}, struct {
        fn lt(_: void, a: VendorEntry, c: VendorEntry) bool {
            if (!std.mem.eql(u8, a.stem, c.stem)) return std.mem.lessThan(u8, a.stem, c.stem);
            // Same stem (e.g. curated `Node` vs `github/Node`): the namespace-less
            // curated entry sorts first, so `find` resolves a bare name to it.
            return a.namespace.len == 0 and c.namespace.len != 0;
        }
    }.lt);

    const wf = b.addWriteFiles();
    for (entries.items) |e| {
        _ = wf.addCopyFile(b.path(e.source_path), e.source_path);
    }

    var aw: std.Io.Writer.Allocating = .init(b.allocator);
    defer aw.deinit();
    const w = &aw.writer;

    w.writeAll(
        \\// AUTO-GENERATED by build.zig. Do not edit.
        \\pub const Template = struct {
        \\    namespace: []const u8,
        \\    name: []const u8,
        \\    display_name: []const u8,
        \\    content: []const u8,
        \\};
        \\
        \\pub const all = [_]Template{
        \\
    ) catch @panic("write");

    for (entries.items) |e| {
        // No namespace → bare display name; otherwise `namespace/stem`.
        if (e.namespace.len == 0) {
            w.print(
                "    .{{ .namespace = \"\", .name = \"{s}\", .display_name = \"{s}\", .content = @embedFile(\"{s}\") }},\n",
                .{ e.stem, e.stem, e.source_path },
            ) catch @panic("write");
        } else {
            w.print(
                "    .{{ .namespace = \"{s}\", .name = \"{s}\", .display_name = \"{s}/{s}\", .content = @embedFile(\"{s}\") }},\n",
                .{ e.namespace, e.stem, e.namespace, e.stem, e.source_path },
            ) catch @panic("write");
        }
    }
    w.writeAll("};\n") catch @panic("write");

    // The check-staged baseline isn't a user-facing template; embed it as a
    // standalone constant so it never appears in `list` or the picker.
    const core_src = "src/internal_templates/check_staged_core.gitignore";
    _ = wf.addCopyFile(b.path(core_src), core_src);
    w.print(
        "\npub const check_staged_core: []const u8 = @embedFile(\"{s}\");\n",
        .{core_src},
    ) catch @panic("write");

    return wf.add("templates_data.zig", aw.written());
}

// Embed the shell-completion scripts into the binary so `zignore completion
// <shell>` can print them with no runtime filesystem dependency. The three
// files live under completions/ in the source tree; this step copies them
// into a synthetic WriteFiles dir and emits a tiny `completions_data.zig`
// module exposing each script as a `pub const` byte slice.
fn generateCompletionsModule(b: *std.Build) std.Build.LazyPath {
    const entries = [_]struct { name: []const u8, file: []const u8 }{
        .{ .name = "bash", .file = "zignore.bash" },
        .{ .name = "zsh", .file = "zignore.zsh" },
        .{ .name = "fish", .file = "zignore.fish" },
    };

    const wf = b.addWriteFiles();
    for (entries) |e| {
        const src = b.fmt("completions/{s}", .{e.file});
        _ = wf.addCopyFile(b.path(src), src);
    }

    var aw: std.Io.Writer.Allocating = .init(b.allocator);
    defer aw.deinit();
    const w = &aw.writer;

    w.writeAll(
        \\// AUTO-GENERATED by build.zig. Do not edit.
        \\
    ) catch @panic("write");

    for (entries) |e| {
        w.print(
            "pub const {s}: []const u8 = @embedFile(\"completions/{s}\");\n",
            .{ e.name, e.file },
        ) catch @panic("write");
    }

    return wf.add("completions_data.zig", aw.written());
}

fn collectVendor(
    b: *std.Build,
    namespace: []const u8,
    subdir: []const u8,
    entries: *std.ArrayList(VendorEntry),
    seen: *std.StringHashMap(void),
) void {
    const io = b.graph.io;
    const path = if (subdir.len == 0)
        "vendor/github/gitignore"
    else
        b.fmt("vendor/github/gitignore/{s}", .{subdir});

    var dir = std.Io.Dir.openDir(.cwd(), io, b.pathFromRoot(path), .{ .iterate = true }) catch |err|
        std.debug.panic("open {s}: {s}", .{ path, @errorName(err) });
    defer dir.close(io);

    var idir = dir.openDir(io, ".", .{ .iterate = true }) catch |err|
        std.debug.panic("reopen {s}: {s}", .{ path, @errorName(err) });
    defer idir.close(io);

    var it = idir.iterate();
    while (it.next(io) catch |err| std.debug.panic("iter {s}: {s}", .{ path, @errorName(err) })) |entry| {
        if (entry.kind != .file) continue;
        if (!std.mem.endsWith(u8, entry.name, ".gitignore")) continue;
        const fname = b.dupe(entry.name);
        const stem = fname[0 .. fname.len - ".gitignore".len];
        if (stem.len == 0) continue; // skip a literal ".gitignore"

        const lower = b.allocator.alloc(u8, stem.len) catch @panic("OOM");
        for (stem, 0..) |c, i| lower[i] = std.ascii.toLower(c);
        const key = b.fmt("{s}/{s}", .{ namespace, lower });
        const gop = seen.getOrPut(key) catch @panic("OOM");
        if (gop.found_existing) {
            b.allocator.free(lower);
            continue;
        }

        const source_path = if (subdir.len == 0)
            b.fmt("vendor/github/gitignore/{s}", .{fname})
        else
            b.fmt("vendor/github/gitignore/{s}/{s}", .{ subdir, fname });
        entries.append(b.allocator, .{ .namespace = namespace, .stem = stem, .source_path = source_path }) catch @panic("OOM");
    }
}

fn collectInternal(
    b: *std.Build,
    entries: *std.ArrayList(VendorEntry),
    seen: *std.StringHashMap(void),
) void {
    const io = b.graph.io;
    const path = "src/internal_templates";

    var dir = std.Io.Dir.openDir(.cwd(), io, b.pathFromRoot(path), .{ .iterate = true }) catch |err|
        std.debug.panic("open {s}: {s}", .{ path, @errorName(err) });
    defer dir.close(io);

    var it = dir.iterate();
    while (it.next(io) catch |err| std.debug.panic("iter {s}: {s}", .{ path, @errorName(err) })) |entry| {
        if (entry.kind != .file) continue;
        if (!std.mem.endsWith(u8, entry.name, ".gitignore")) continue;

        const fname = b.dupe(entry.name);
        var stem = fname[0 .. fname.len - ".gitignore".len];

        // The conservative check-staged baseline is embedded separately (see
        // generateTemplatesModule); it's not a user-facing template.
        if (std.mem.eql(u8, stem, "check_staged_core")) continue;

        // Curated internal templates carry no namespace: they resolve by their
        // bare name and render without a `namespace/` display prefix.
        const namespace: []const u8 = "";
        // Capitalize first letter for display
        const capitalized = b.allocator.alloc(u8, stem.len) catch @panic("OOM");
        @memcpy(capitalized, stem);
        capitalized[0] = std.ascii.toUpper(capitalized[0]);
        // Handle special cases like c++
        if (std.mem.eql(u8, stem, "c++")) {
            capitalized[0] = 'C';
            capitalized[1] = '+';
            capitalized[2] = '+';
        } else if (std.mem.eql(u8, stem, "macos")) {
            @memcpy(capitalized, "macOS");
        } else if (std.mem.eql(u8, stem, "visualstudiocode")) {
            @memcpy(capitalized, "VisualStudioCode");
        } else if (std.mem.eql(u8, stem, "vim")) {
            @memcpy(capitalized, "Vim");
        } else if (std.mem.eql(u8, stem, "linux")) {
            @memcpy(capitalized, "Linux");
        } else if (std.mem.eql(u8, stem, "windows")) {
            @memcpy(capitalized, "Windows");
        } else if (std.mem.eql(u8, stem, "cmake")) {
            @memcpy(capitalized, "CMake");
        } else if (std.mem.eql(u8, stem, "php")) {
            @memcpy(capitalized, "PHP");
        }
        stem = capitalized;

        const lower = b.allocator.alloc(u8, stem.len) catch @panic("OOM");
        for (stem, 0..) |c, i| lower[i] = std.ascii.toLower(c);
        const key = b.fmt("{s}/{s}", .{ namespace, lower });
        const gop = seen.getOrPut(key) catch @panic("OOM");
        if (gop.found_existing) {
            b.allocator.free(lower);
            continue;
        }

        const source_path = b.fmt("{s}/{s}", .{ path, fname });
        entries.append(b.allocator, .{ .namespace = namespace, .stem = stem, .source_path = source_path }) catch @panic("OOM");
    }
}
